/**
 * Noms français des exercices du catalogue.
 *
 * Le catalogue est anglais, et il le reste **dans les données** : c'est le nom
 * anglais qui identifie un mouvement dans le programme comme dans l'historique,
 * et renommer à la source couperait la courbe de progression en deux — les
 * séances d'avant sous un nom, celles d'après sous un autre. La traduction se
 * fait donc à l'affichage seulement, par ce dictionnaire.
 *
 * Couvre les 190 mouvements que le générateur peut poser — toutes les
 * combinaisons de type, fréquence, niveau, lieu, matériel et durée, plus les
 * journées composées à la main. Un mouvement choisi dans le sélecteur hors de
 * cette liste garde son nom anglais : mieux qu'une traduction automatique
 * fausse.
 */
export const FRENCH_NAMES: Record<string, string> = {
  "3/4 Sit-Up": "Relevé de buste 3/4",
  "Air Bike": "Pédalage au sol",
  "Alternate Hammer Curl": "Curl marteau alterné",
  "Alternate Heel Touchers": "Touchers de talons alternés",
  "Alternate Incline Dumbbell Curl": "Curl incliné alterné haltères",
  "Alternate Leg Diagonal Bound": "Bonds diagonaux alternés",
  "Alternating Cable Shoulder Press": "Développé épaules alterné poulie",
  "Alternating Deltoid Raise": "Élévations alternées (deltoïdes)",
  "Anti-Gravity Press": "Développé anti-gravité (nuque, banc incliné)",
  "Back Flyes - With Bands": "Oiseau à l'élastique",
  "Band Skull Crusher": "Barre au front à l'élastique",
  "Barbell Bench Press - Medium Grip": "Développé couché barre",
  "Barbell Curl": "Curl barre",
  "Barbell Curls Lying Against An Incline": "Curl barre allongé sur banc incliné",
  "Barbell Deadlift": "Soulevé de terre barre",
  "Barbell Incline Bench Press - Medium Grip": "Développé incliné barre",
  "Barbell Incline Shoulder Raise": "Élévation d'épaules barre, banc incliné",
  "Barbell Rear Delt Row": "Rowing barre deltoïdes postérieurs",
  "Barbell Seated Calf Raise": "Mollets assis barre",
  "Barbell Shrug": "Haussements d'épaules barre",
  "Barbell Shrug Behind The Back": "Haussements d'épaules barre derrière le dos",
  "Barbell Side Bend": "Flexion latérale barre",
  "Barbell Side Split Squat": "Squat latéral barre",
  "Barbell Squat": "Squat barre",
  "Barbell Walking Lunge": "Fentes marchées barre",
  "Bench Dips": "Dips sur banc",
  "Bench Press - With Bands": "Développé couché à l'élastique",
  "Bent Over Barbell Row": "Rowing barre buste penché",
  "Bent Over Dumbbell Rear Delt Raise With Head On Bench": "Oiseau haltères, tête posée sur banc",
  "Bent Over Low-Pulley Side Lateral": "Oiseau à la poulie basse",
  "Bent Over One-Arm Long Bar Row": "Rowing un bras à la barre longue",
  "Bent Over Two-Dumbbell Row": "Rowing haltères buste penché",
  "Bent Over Two-Dumbbell Row With Palms In": "Rowing haltères prise neutre",
  "Bent-Knee Hip Raise": "Relevé de bassin genoux fléchis",
  "Bicycling, Stationary": "Vélo d'appartement",
  "Body Tricep Press": "Extension triceps au poids du corps",
  "Body-Up": "Body-up (planche vers pompe sur coudes)",
  "Bodyweight Squat": "Squat au poids du corps",
  "Bodyweight Walking Lunge": "Fentes marchées au poids du corps",
  "Bosu Ball Cable Crunch With Side Bends": "Crunch poulie sur Bosu avec flexions latérales",
  "Bottoms Up": "Relevé de jambes tendues au sol",
  "Bradford/Rocky Presses": "Développé Bradford (avant-arrière)",
  "Butt Lift (Bridge)": "Pont fessier",
  "Butt-Ups": "Relevés de bassin en planche",
  "Butterfly": "Butterfly (pec deck)",
  "Cable Chest Press": "Développé poitrine à la poulie",
  "Cable Crossover": "Écarté poulie vis-à-vis",
  "Cable Crunch": "Crunch à la poulie",
  "Cable Deadlifts": "Soulevé de terre à la poulie",
  "Cable Hammer Curls - Rope Attachment": "Curl marteau poulie (corde)",
  "Cable Hip Adduction": "Adduction de hanche à la poulie",
  "Cable Incline Pushdown": "Tirage bras tendus incliné à la poulie",
  "Cable Incline Triceps Extension": "Extension triceps incliné à la poulie",
  "Cable Internal Rotation": "Rotation interne à la poulie",
  "Cable Iron Cross": "Croix de fer à la poulie",
  "Cable Judo Flip": "Judo flip à la poulie",
  "Cable Lying Triceps Extension": "Extension triceps allongé à la poulie",
  "Cable One Arm Tricep Extension": "Extension triceps un bras à la poulie",
  "Cable Preacher Curl": "Curl pupitre à la poulie",
  "Cable Rear Delt Fly": "Oiseau à la poulie",
  "Cable Reverse Crunch": "Crunch inversé à la poulie",
  "Cable Rope Overhead Triceps Extension": "Extension triceps nuque poulie (corde)",
  "Cable Seated Crunch": "Crunch assis à la poulie",
  "Cable Seated Lateral Raise": "Élévations latérales assis à la poulie",
  "Cable Shrugs": "Haussements d'épaules à la poulie",
  "Cable Wrist Curl": "Curl poignets à la poulie",
  "Calf Press": "Presse à mollets",
  "Calf Press On The Leg Press Machine": "Mollets à la presse à cuisses",
  "Calf-Machine Shoulder Shrug": "Haussements d'épaules à la machine à mollets",
  "Car Drivers": "Volant (rotations disque bras tendus)",
  "Chin-Up": "Traction supination",
  "Clock Push-Up": "Pompes en horloge",
  "Close-Grip Barbell Bench Press": "Développé couché prise serrée",
  "Close-Grip Dumbbell Press": "Développé haltères prise serrée",
  "Close-Grip EZ Bar Curl": "Curl barre EZ prise serrée",
  "Close-Grip EZ-Bar Curl with Band": "Curl barre EZ prise serrée + élastique",
  "Close-Grip EZ-Bar Press": "Développé barre EZ prise serrée",
  "Close-Grip Front Lat Pulldown": "Tirage vertical prise serrée",
  "Close-Grip Push-Up off of a Dumbbell": "Pompes serrées sur un haltère",
  "Cocoons": "Cocons (enroulement complet)",
  "Cross Over - With Bands": "Écarté vis-à-vis à l'élastique",
  "Crunch - Hands Overhead": "Crunch bras tendus au-dessus de la tête",
  "Crunch - Legs On Exercise Ball": "Crunch jambes sur Swiss ball",
  "Crunches": "Crunchs",
  "Deadlift with Bands": "Soulevé de terre avec élastiques",
  "Decline Barbell Bench Press": "Développé décliné barre",
  "Decline Dumbbell Bench Press": "Développé décliné haltères",
  "Decline Dumbbell Flyes": "Écarté décliné haltères",
  "Decline Dumbbell Triceps Extension": "Extension triceps décliné haltères",
  "Decline Push-Up": "Pompes déclinées (pieds surélevés)",
  "Deficit Deadlift": "Soulevé de terre en déficit",
  "Dip Machine": "Dips à la machine",
  "Dips - Triceps Version": "Dips (version triceps)",
  "Double Leg Butt Kick": "Talons-fesses sautés",
  "Drag Curl": "Curl barre glissé (drag curl)",
  "Dumbbell Flyes": "Écarté couché haltères",
  "Dumbbell Seated One-Leg Calf Raise": "Mollets assis une jambe haltère",
  "Dumbbell Shrug": "Haussements d'épaules haltères",
  "External Rotation with Band": "Rotation externe à l'élastique",
  "Fast Skipping": "Corde à sauter rapide",
  "Finger Curls": "Curl des doigts",
  "Flat Bench Lying Leg Raise": "Relevé de jambes allongé sur banc",
  "Floor Glute-Ham Raise": "Glute-ham raise au sol",
  "Flutter Kicks": "Battements de jambes",
  "Freehand Jump Squat": "Squat sauté",
  "Glute Kickback": "Kickback fessier",
  "Handstand Push-Ups": "Pompes en équilibre sur les mains",
  "High Cable Curls": "Curl poulie haute",
  "Hip Extension with Bands": "Extension de hanche à l'élastique",
  "Hip Flexion with Band": "Flexion de hanche à l'élastique",
  "Hip Lift with Band": "Relevé de bassin à l'élastique",
  "Hyperextensions With No Hyperextension Bench": "Extensions lombaires au sol",
  "Incline Bench Pull": "Rowing barre sur banc incliné",
  "Incline Push-Up": "Pompes inclinées (mains surélevées)",
  "Incline Push-Up Close-Grip": "Pompes inclinées prise serrée",
  "Incline Push-Up Medium": "Pompes inclinées prise moyenne",
  "Incline Push-Up Reverse Grip": "Pompes inclinées prise inversée",
  "Incline Push-Up Wide": "Pompes inclinées prise large",
  "Inverted Row": "Rowing inversé (sous une barre)",
  "Isometric Chest Squeezes": "Contraction isométrique des pectoraux",
  "Isometric Wipers": "Essuie-glaces isométriques",
  "Janda Sit-Up": "Relevé de buste Janda",
  "Jogging, Treadmill": "Jogging sur tapis",
  "Knee Tuck Jump": "Sauts groupés",
  "Kneeling Arm Drill": "Travail des bras à genoux (sprint)",
  "Leg Extensions": "Leg extension",
  "Leg Lift": "Relevé de jambes",
  "Leverage Shrug": "Haussements d'épaules à la machine",
  "Linear 3-Part Start Technique": "Technique de départ en trois temps",
  "Linear Acceleration Wall Drill": "Montées de genoux contre un mur",
  "Low Cable Crossover": "Écarté poulie basse",
  "Lying Cambered Barbell Row": "Rowing barre cambrée allongé",
  "Lying Leg Curls": "Leg curl allongé",
  "Middle Back Shrug": "Haussements d'épaules milieu du dos (banc incliné)",
  "Mountain Climbers": "Mountain climbers",
  "Moving Claw Series": "Griffes en mouvement (sprint)",
  "Natural Glute Ham Raise": "Glute-ham raise naturel",
  "One-Arm Flat Bench Dumbbell Flye": "Écarté un bras haltère",
  "One-Legged Cable Kickback": "Kickback une jambe à la poulie",
  "Palms-Down Dumbbell Wrist Curl Over A Bench": "Curl poignets haltère en pronation sur banc",
  "Palms-Down Wrist Curl Over A Bench": "Curl poignets barre en pronation sur banc",
  "Palms-Up Barbell Wrist Curl Over A Bench": "Curl poignets barre en supination sur banc",
  "Palms-Up Dumbbell Wrist Curl Over A Bench": "Curl poignets haltère en supination sur banc",
  "Plank": "Planche",
  "Plyo Push-up": "Pompes pliométriques",
  "Prone Manual Hamstring": "Leg curl manuel (avec partenaire)",
  "Pull Through": "Pull-through à la poulie",
  "Pullups": "Tractions",
  "Push Up to Side Plank": "Pompe puis planche latérale",
  "Push-Up Wide": "Pompes prise large",
  "Push-Ups - Close Triceps Position": "Pompes serrées (triceps)",
  "Push-Ups With Feet Elevated": "Pompes pieds surélevés",
  "Pushups": "Pompes",
  "Pushups (Close and Wide Hand Positions)": "Pompes (mains serrées et larges)",
  "Rack Pull with Bands": "Rack pull avec élastiques",
  "Rack Pulls": "Rack pull (soulevé de terre partiel)",
  "Recumbent Bike": "Vélo semi-allongé",
  "Reverse Hyperextension": "Hyperextension inversée",
  "Rocket Jump": "Saut fusée",
  "Rocking Standing Calf Raise": "Mollets debout en balancier",
  "Rope Straight-Arm Pulldown": "Tirage bras tendus à la corde",
  "Running, Treadmill": "Course sur tapis",
  "Russian Twist": "Russian twist",
  "Scissors Jump": "Fentes sautées (ciseaux)",
  "Seated Calf Raise": "Mollets assis à la machine",
  "Seated Dumbbell Palms-Down Wrist Curl": "Curl poignets assis haltère en pronation",
  "Seated Dumbbell Palms-Up Wrist Curl": "Curl poignets assis haltère en supination",
  "Seated Good Mornings": "Good morning assis",
  "Seated Leg Curl": "Leg curl assis",
  "Shoulder Press - With Bands": "Développé épaules à l'élastique",
  "Single Leg Glute Bridge": "Pont fessier une jambe",
  "Single-Arm Push-Up": "Pompes à un bras",
  "Single-Leg Leg Extension": "Leg extension une jambe",
  "Smith Machine Calf Raise": "Mollets debout à la Smith machine",
  "Smith Machine Reverse Calf Raises": "Mollets inversés à la Smith machine",
  "Smith Machine Stiff-Legged Deadlift": "Soulevé de terre jambes tendues Smith machine",
  "Smith Machine Upright Row": "Rowing menton Smith machine",
  "Speed Band Overhead Triceps": "Extension triceps nuque rapide à l'élastique",
  "Split Jump": "Fentes sautées",
  "Squats - With Bands": "Squat à l'élastique",
  "Standing Dumbbell Upright Row": "Rowing menton haltères",
  "Standing Leg Curl": "Leg curl debout",
  "Standing Towel Triceps Extension": "Extension triceps avec serviette",
  "Step-up with Knee Raise": "Montée sur step avec genou levé",
  "Stiff Leg Barbell Good Morning": "Good morning jambes tendues",
  "Stiff-Legged Dumbbell Deadlift": "Soulevé de terre jambes tendues haltères",
  "Straight-Arm Pulldown": "Tirage bras tendus à la poulie",
  "Trail Running/Walking": "Course ou marche en sentier",
  "V-Bar Pullup": "Tractions à la barre en V",
  "Wide-Grip Rear Pull-Up": "Tractions prise large nuque",
};

/** Le nom à afficher : la traduction quand elle existe, sinon l'original. */
export function frenchName(name: string): string {
  return FRENCH_NAMES[name] ?? name;
}
