import { parseDeloads, startDeload, stopDeload, activeDeload, purgeExpired, deloadWeight, inDeload, DELOAD_DAYS } from "../.tests-build/deload.mjs";
let ko = 0;
const eq = (nom, a, b) => { const ok = JSON.stringify(a) === JSON.stringify(b); if (!ok) { ko++; console.log(`✗ ${nom}\n   attendu ${JSON.stringify(b)}\n   obtenu  ${JSON.stringify(a)}`); } else console.log(`✓ ${nom}`); };
const t0 = new Date("2026-09-14T12:00:00Z");
const l = startDeload([], "Squat", t0);
eq("une semaine", (Date.parse(l[0].until) - Date.parse(l[0].from)) / 86400000, DELOAD_DAYS);
eq("actif le jour même", activeDeload(l, "Squat", t0)?.exerciseName, "Squat");
eq("actif le sixième jour", activeDeload(l, "Squat", new Date("2026-09-20T12:00:00Z"))?.factor, 0.9);
eq("fini le septième", activeDeload(l, "Squat", new Date("2026-09-21T12:00:00Z")), null);
eq("autre exercice : rien", activeDeload(l, "Curl", t0), null);
eq("relancer remplace", startDeload(l, "Squat", new Date("2026-09-16T12:00:00Z")).length, 1);
eq("deux exercices coexistent", startDeload(l, "Curl", t0).length, 2);
eq("arrêt", stopDeload(l, "Squat"), []);
eq("purge des finis", purgeExpired(l, new Date("2026-09-22T00:00:00Z")), []);
eq("purge garde les actifs", purgeExpired(l, t0).length, 1);
eq("charge allégée aux disques : 65 → 57,5", deloadWeight(65), 57.5);
eq("100 → 90", deloadWeight(100), 90);
eq("facteur réglable", deloadWeight(100, 0.8), 80);
eq("séance pendant l'allègement", inDeload(l, "Squat", "2026-09-17T10:00:00Z"), true);
eq("séance après", inDeload(l, "Squat", "2026-09-25T10:00:00Z"), false);
eq("relecture valide", parseDeloads(l).length, 1);
eq("relecture : facteur absurde remplacé", parseDeloads([{ ...l[0], factor: 3 }])[0].factor, 0.9);
eq("relecture : date invalide écartée", parseDeloads([{ ...l[0], until: "hier" }]), []);
eq("relecture : non-liste", parseDeloads({}), null);
console.log(ko ? `\n${ko} échec(s)` : "\nTout passe");
process.exit(ko ? 1 : 0);
